/* import './globals.css' */
import { cn } from "@/lib/utils"
import "../styles/globals.css"
import { Inter } from 'next/font/google'
import Provider from "@/components/Provider"
import Navbar from "@/components/Navbar"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en"
            className={cn('bg-white text-slate-900 antialiased'
                , inter.className)}
        >
            <body className="min-h-screen bg-slate-50 dark:bg-slate-900">
                <Provider>
                    {/* @ts-expect-error */}
                    <Navbar />
                    {/* <Toaster position='bottom-right' /> */}
                    <main className="pt-[6rem]">
                        {children}
                    </main>
                </Provider>
            </body>
        </html>
    )
}
